 //Directly to backend
#@port = 3000 
// Load balancer
@port = 9999  


POST http://localhost:{{port}}/payments
Content-Type: application/json

{
    "correlationId": "{{$guid}}",
    "amount": 19.90
}

###
GET http://localhost:{{port}}/payments-summary 

###
GET http://localhost:{{port}}/payments-summary?from=2025-07-29T13:00:00.000Z&to=2025-07-29T23:07:00.000Z
