services:
  api01: &api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api01
    environment:
      - INSTANCE_NAME=api01
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.675"
          memory: "160MB"

  api02:
    <<: *api
    container_name: api02
    environment:
      - INSTANCE_NAME=api02

  nginx:
    image: nginx:alpine-slim
    container_name: load-balancer
    ports:
      - "9999:9999"
    networks:
      - rinha-net
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "15MB"

networks:
  payment-processor:
    external: true
  rinha-net:
    driver: bridge
